### ISSUE TITLE
 Antd library with reactql starter ? 

### ISSUE THREAD

**Issue by code2end** [leebenson/reactql#121]
Can you help me figuring out , how to configure [babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import) for antd-css ?

I'm new to webpack and cant figure out how to implement the solution for this starter, any help or direction would do good.
Please refer this I'm facing the similar [issue](https://github.com/ant-design/ant-design/issues/5132) for more details.

Cheers for the starter 👍

**Comment by leebenson** [comment]
I don't have any experience with antd, so this is probably something best left to the community. 

If you want to attempt it yourself, [src/webpack/css.ts](https://github.com/leebenson/reactql/blob/master/src/webpack/css.ts) is where CSS is configured, and [src/webpack/common.ts](https://github.com/leebenson/reactql/blob/master/src/webpack/common.ts) is where universal loaders typically go (Babel plugins, etc.)

**Comment by code2end** [comment]
Okay thanks , I will look into it .

@leebenson Have you explored next.js with universal apollo ?

**Comment by leebenson** [comment]
Seen it, yes. Explored it, no. Next.js is a framework with overlapping features vs ReactQL. You'd pick one or the other for a project - it's either/or, just like you'd pick either Apollo _or_ Relay, but generally not the two together.

I wrote ReactQL because I don't like using frameworks, and prefer to work with - and know intimately -the choices in my stack. ReactQL is squarely a starter kit, whereas Next.js is more like a framework.

**Comment by leebenson** [comment]
I'll close this for now, since it's not an issue, per se, but a specific customisation request. You might find StackOverflow gets your Q in front of a larger audience.

**Comment by jppgks** [comment]
FYI, the only edits I needed to make for ReactQL to work with antd is:

```shell
yarn add antd
```

and then add the import to `styles.global.scss`:
```css
@import '~antd/dist/antd.css';
```
