### ISSUE TITLE
Updating ReactQL?

### ISSUE THREAD

**Issue by bmschwartz** [leebenson/reactql#128]
How can I keep ReactQL updated in my project? I've been downloading the new zip and using a diff checker/editor called [Kaleidoscope](https://www.kaleidoscopeapp.com/) but it's a little tedious. IIRC the old CLI made this pretty easy.

**Comment by dotansimha** [comment]
@leebenson, I can suggest a possible solution. 
React native has a solution for updating the boilerplate code after the initial creation, using git diff/merge. 
You can read more about it here: https://facebook.github.io/react-native/docs/upgrading#upgrade-based-on-git 

From my experience with it, it's very easy to use and works without conflicts for 99% of the cases.

**Comment by leebenson** [comment]
I've been back and forth on strategies for upgrading, and honestly, haven't figured out a good way to do it cleanly yet.

In past versions, ReactQL specific code was neatly separate out in a `kit` folder. Userland source was placed in `src`. Interacting with the kit was a case of having a 'main' React entrypoint at a defined file in the src folder. There was also a basic API for doing things like setting config files, etc.

Because of that relatively clean separation, the CLI was simple to upgrade; it preserved `src` and updated all the files around it.

In _this_ version, the lines are a lot blurrier between 'kit' and 'user source'. I've done away with the config API on purpose, and instead actively encourage directly editing Webpack, Apollo set-up files, etc. The reason being, I want to promote ReactQL squarely as a starter kit, and not a framework. There will more than likely be parts that aren't applicable to any given project... these are details that should be tweaked by the end-dev, and not abstracted away behind unnecessary APIs.

So for now, Kaleidoscope is probably the best way to do it (and incidentally, is exactly how I upgrade my own personal projects built on top of ReactQL.) It's slightly more tedious than firing off a CLI command, but importantly, it forces the dev to _understand_ what may have changed between versions, and whether those changes / upgrades are warranted or even applicable.

I'm open to suggests/PRs on how to best play this; TBH, I've not given this area any real thought/effort, so undoubtedly there will be strategies I've not considered. Something like @dotansimha's approach could be ideal, if we can package it easily enough and get it working for the vast majority of cases. What I want to avoid is a user _thinking_ they're just upgrading the core, but potentially blowing up their code in the process if significant drift is introduced between versions, or has been heavily customised locally.

Open to PRs!
