### ISSUE TITLE
App exceeding Heroku Memory Quota of 512 MB

### ISSUE THREAD

**Issue by ponty96** [leebenson/reactql#142]
I just deployed an app using this boilerplate, it works probably when I run `npm run production` on my Mac OS X but on Heroku I get this(attached image) error

<img width="974" alt="screen shot 2019-01-24 at 2 45 58 am" src="https://user-images.githubusercontent.com/11190968/51648830-73c4d600-1f82-11e9-9c15-914c94fe62d1.png">

**Comment by Ciberusps** [comment]
Try to restart all dynos 
![image](https://user-images.githubusercontent.com/14001879/51670679-35f29c80-1fd8-11e9-8eb4-c8d11f009f09.png)

**Comment by leebenson** [comment]
Node is quite memory-intensive. It's normal for a single Node.js process, serving no traffic, to eat 200-400mb idly in between GC events.

During compilation, this can balloon by 100mb+ with the potential of multiple processes being spawned to transpile concurrently, and execute binaries for gzip compression, etc.

On my Macbook Pro running Node 11.6, this usually settles down to ~200mb after compilation.

Since much of that 512mb is likely already taken with the underlying OS and other libs, it's not surprising therefore that you're running into memory issues.

I'd recommend at least 1GB - and 2-4GB min in production.
