### ISSUE TITLE
Question: Is go to definition supposed to work for generated types?

### ISSUE THREAD

**Issue by andrejohansson** [leebenson/reactql#160]
Hello,

First of, thank you for this rich starter kit.
I'm very new to both typescript and graphql and have a beginner question that most likely is trivial to answer. 

Generating types from a graphql schema and then using them in components. I expected editors (such as vscode or webstorm) to be able to infer the type and havethings like intellisense and "go to type definition".

However in one place where I wanted these capabilities, it does not work.

In the example [hackernews component](https://github.com/leebenson/reactql/blob/b6a4d8c58661541777dc83deb68f76e25026d581/src/components/example/hackernews.tsx#L58) I get the following information in vscode when hovering:
![image](https://user-images.githubusercontent.com/2828428/56433864-b91f4800-62d2-11e9-9dae-5dc97c4d70f5.png)

So, it seems that there is a type on the variable ``data`` and all is well. However, if I right click and choose "Go To Type Definition" it cannot find any type definition. 

Intellisense (writing ``data.`` and pressing space) is not giving me correct information either. I was expecting to see ``hn`` since the generated type definition for ``GetHackerNewsTopStoriesQuery`` looks like this:

![image](https://user-images.githubusercontent.com/2828428/56434192-e0c2e000-62d3-11e9-95df-2bdb2998df6d.png)

Is this expected behavior, some editor setting or a project configuration I'm missing? Or am I misunderstanding the format of the generated graphql typescript classes?

P.S. This question may or may not belong in the respective editors trackers

**Comment by leebenson** [comment]
The reason `data` isn't giving you Intellisense is because the `Maybe<T>` type provided by [GraphQL Code Generator](https://graphql-code-generator.com/) means the type is `T | null`, so data might not return anything. Which is true - if the query fails, `data` could well be empty.

You have two options to fix this:

1. Recommended: Do an explicit `if (data)` check. This will infer that anything within the `if` block is valid, so `data.*` will be recognised.

2. If you know `data` is _definitely_ not null (and there's really no way to know that for sure, if the GraphQL schema is indicating that `data` is nullable - e.g. in the case of an error), you can do `data!` to override its nullability and inform TS that it should assume it's not null. I don't recommend this approach, since it can blow-up at runtime if what's returned is different from what you expect!

Re: jumping to the correct type definition, I'm afraid I'm not privy to the inner workings of VSCode's code resolution with that, so that's probably best asked in the relevant repo.
