### ISSUE TITLE
Hydrate on Static Deploy

### ISSUE THREAD

**Issue by jasonlor** [leebenson/reactql#170]
Hey there!

Is it possible to hydrate in static mode? The only reference I was able to find is
I want to leverage a different backend than Koa and SSR render the data from the server.

ReactDOM[root.innerHTML ? "hydrate" : "render"] in client.tsx

**Comment by leebenson** [comment]
I'm not sure what you mean, exactly.

Static mode, by definition, means that the output being produced includes:

- A very bare-bones `index.html`, used to bootstrap...
- main.js
- main.css

In this context, there's nothing to hydrate because `index.html` doesn't contain any rendered React HTML. It contains an empty `<div id="root">` where it will render the client-side React.

If you are foregoing the index.html and using your own backend, this placing your _own_ SSR content inside of `<div id="root">` will have the same affect. However, it would need to match the generated .js exactly, or you'll get errors that the content doesn't match.

If I'm missing the point and you mean something else, please provide some more detail. I'm not clear how you're expecting this to work.
