### ISSUE TITLE
Warning: Expected server HTML to contain a matching <div> in <div>.

### ISSUE THREAD

**Issue by blntylmn** [leebenson/reactql#86]
Just follow the instructions and create a new project. Change nothing and run it. I'm getting this warning on browser console which is seems like something is inconsistent between server and client renders.
Is this warning does matters or should I just ignore it ?

**Comment by leebenson** [comment]
You can ignore the warning in development (port 8080). It's likely occurring because we're using `reactDOM.hydrate()` to render the initial React to the DOM, which expects that we're first receiving that data from the server. Since browser-only development doesn't have any server output, we get the warning.

This can be fixed by changing the `doRender()` function inside of [kit/entry/browser.js](https://github.com/reactql/kit/blob/master/kit/entry/browser.js#L58-L63) to:

```
function doRender() {
  const main = document.getElementById('main');
  const renderOrHydrate = main.innerHTML.trim().length ? 'hydrate' : 'render';
  ReactDOM[renderOrHydrate](
    <Root />,
    main,
  );
}
```

... which will default to the `.render()` method instead when there's no HTML output to rehydrate.

**Comment by leebenson** [comment]
I'll make the change in the next version of the kit, but you can edit `kit/entry/browser.js` manually to achieve the same in the meantime.

**Comment by blntylmn** [comment]
Thanks that dissapered the warning.
Great job btw. This kit is already awesome and I believe has more potential to bring more on table in future !

**Comment by leebenson** [comment]
Thanks @blntylmn. I'll be releasing the next major release of the kit in a few weeks, which will bring some significant improvements. Watch this space!

**Comment by blntylmn** [comment]
Watching closely 👍

**Comment by clodal** [comment]
A similar implementation cited from @mattyfresh in https://github.com/nozzle/react-static/issues/144, not sure which is preferred, just throwing it here!

```
// kit/browser.js
function doRender() {
  const renderMethod = module.hot ? ReactDOM.render : ReactDOM.hydrate;
  renderMethod(
    <Root />,
    document.getElementById('main'),
  );
}
```

**Comment by leebenson** [comment]
This has totally gone in the new 3.0.0 kit, so I'll close now.
